batch_size: 2

grid_size: 7
n_predictors: 2

lambda_coord: 5.0
lambda_noobj: 0.5

n_classes: 20

momentum: 0.9
weight_decay: 0.0005
learning_rate: 0.0005
lr_decay: 0.0005

backbone:
  in_channels: 3
  # convolutional blocks
  conv_blocks:
    # DarkNet layers
    - n_layers: 1
      layers:
        - [64, 7, 2, 1]
    - n_layers: 1
      layers:
        - [192, 3, 1, 1]
    - n_layers: 4
      layers:
        - [128, 1, 1, 1]
        - [256, 3, 1, 1]
        - [256, 1, 1, 1]
        - [512, 3, 1, 1]
    - n_layers: 10
      layers:
        - [256, 1, 1, 1]
        - [512, 3, 1, 1]
        - [256, 1, 1, 1]
        - [512, 3, 1, 1]
        - [256, 1, 1, 1]
        - [512, 3, 1, 1]
        - [256, 1, 1, 1]
        - [512, 3, 1, 1]
        - [512, 1, 1, 1]
        - [1024, 3, 1, 1]
    - n_layers: 5
      layers:
        - [512, 1, 1, 1]
        - [1024, 3, 1, 1]
        - [512, 1, 1, 1]
        - [1024, 3, 1, 1]
        - [1024, 3, 2, 1]
    - n_layers: 2
      layers:
        - [1024, 3, 1, 1]
        - [1024, 3, 2, 1]

classifier:
  # final YOLO layers
  conv_blocks:
  - n_layers: 1
    layers:
      - [1024, 3, 1, 1]
  - n_layers: 1
    layers:
      - [1024, 3, 2, 1]
  - n_layers: 1
    layers:
      - [1024, 3, 1, 1]
  - n_layers: 1
    layers:
      - [1024, 3, 1, 1]

  # fully-connected layers
  fc_layers:
    dim: 4096
    dropout: 0.5
    # after this, activation, dropout, and another fc layer
    # final fc dimension: S*S*(B*5+C)
